UnfoldedInc/earthengine-layers

- modules/earthengine-layers/src/earth-engine-layer.js
As mentioned in #12 , currently the layer id changes on every call of `_updateEEVisParams`. This creates a static id for each layer, currently the first part of the two 32-character identifiers as mentioned in #12. There might be a better long-term solution but this fixes the current issue.
> Fix tile flicker by creating unique id

- examples/ee-demo/package.json
- modules/earthengine-layers/package.json
- yarn.lock
Looking at the `yarn.lock`, it looks like `0.1.217` was already being used, because of the caret in `^0.1.209`.
> Update @google/earthengine to ^0.1.217

- examples/ee-demo/app.js
- modules/earthengine-layers/src/earth-engine-layer.js
- Rename `data` prop to `eeObject`
- If `eeObject` is a string, this calls `ee.Deserializer.fromJSON` on the string
- Works with the existing app example
> Deserialize ee string

- examples/ee-demo/app.js
- modules/earthengine-layers/src/earth-engine-layer.js
- modules/earthengine-layers/src/ee-api.js
- Updates `EEApi.initialize` to take either a `clientId` or `token`; if `token` is provided it sets the token with `ee` directly. This could be renamed to `accessToken` if we wanted to be more clear that this is the short-lived OAuth token.
- Adds an `_updateToken` step which calls `initialize` with the token if the prop exists and has changed. The full `initialize` step might not need to be called again if it's previously happened and only the token has changed. You might be able to do just `setToken`, which might prevent an extra HTTP call, but I haven't tested this.
The idea is that on the Python side, a class could keep track of when the access token expires, and automatically refresh the token and pass it to JS on the next layer call.
I tested this with a modification of …
> Update ee auth from props.token

- examples/pydeck/Introduction.ipynb
- examples/pydeck/README.md
This adds an example Jupyter notebook for use with Pydeck and the Earth Engine layer. (To view the rendered notebook, [click here](https://nbviewer.jupyter.org/github/kylebarron/earthengine-layers/blob/notebook-example/examples/pydeck/Introduction.ipynb)).
Notes:
- Right now the friction points are:
- Ping the Google OAuth endpoint to get an access token
- Add the custom layer library
- EE object must be serialized
- The serialized EE object must further be wrapped in a pair of _single_ quotes, so that Pydeck interprets it as a literal string. With current Pydeck, wrapping it in double quotes removes every internal double quote, and thus destroys the JSON.
- For now, I load the layer's bundle from a branch on my fork, including #18 . The output of the rollup bundle is currently ignored by …
> Add Pydeck introduction notebook

- examples/pydeck/Introduction.ipynb
This sets the notebook example to use new bundle on `master`, which includes #21 . 
This is tested with a new Python environment, as described [here](https://github.com/UnfoldedInc/earthengine-layers/blob/master/examples/pydeck/README.md), and works successfully.
> Fix jsdelivr url in notebook example

- .gitignore
`.ipynb_checkpoints` are auto-generated files by Jupyter when autosaving. It's [ standard](https://github.com/github/gitignore/blob/2a4de265d37eca626309d8e115218d18985b5435/Python.gitignore#L78-L80) to have in a gitignore.
> Include notebook checkpoints in gitignore

- py/.gitignore
- py/CHANGELOG.md
- py/MANIFEST.in
- py/README.md
- py/examples/Introduction.ipynb
- py/pydeck_earthengine_layers/__init__.py
- py/pydeck_earthengine_layers/pydeck_earthengine_layers.py
- py/requirements.txt
- py/requirements_dev.txt
- py/setup.cfg
- py/setup.py
Simple wrapper class for using Earth Engine in Pydeck
**Handles**
- Loading credentials
- Refreshing access token as needed when it expires
- Serializing EE objects to strings
- Add EE JS bundle to pydeck's custom libraries setting
**Example**
A simpler version of the existing notebook is included ([rendered](https://nbviewer.jupyter.org/github/kylebarron/earthengine-layers/blob/python-wrapper/py/examples/Introduction.ipynb)). Creating the layer simplifies to:
```py
from pydeck_earthengine_layers import EarthEngineLayer
import pydeck as pdk
import ee
ee.Initialize()
image = ee.Image('CGIAR/SRTM90_V4')
ee_layer = EarthEngineLayer(image, vis_params={"min": 0, "max": 255})
```
**Questions**
- Regarding the API, currently `ee_object` is set as the first positional parameter, and optional …
> Python wrapper for Earth Engine Pydeck layer

- py/pydeck_earthengine_layers/pydeck_earthengine_layers.py
The url to retrieve the custom `earthengine-layer` layer bundle is currently hardcoded to the jsdeliver cdn pointing to this master branch. This PR adds an optional argument to the class constructor to point to a custom url. This is helpful for debugging/testing changes, so that I can build a rollup bundle locally, serve it on `localhost`, and point the class to load from `localhost`.
> pydeck: Option to set custom ee layer bundle url

- examples/ee-demo/app.js
- modules/earthengine-layers/src/earth-engine-layer.js
Forwards all props passed to `EarthEngineLayer` down to `TileLayer`. Closes #36 
- Do I need to use `Object.assign` instead of spreading `...this.props`?
- There's still a little bit of "flicker" with alternative `refinementStrategy` methods. For now I have the `ee-demo` example set to `refinementStrategy: 'no-overlap'`.
`refinementStrategy: 'no-overlap'`: Some empty tiles when loading at a new zoom
`refinementStrategy: 'never'`: At every zoom threshold, the entire map is white while tiles load.
> Fix forwarding props to TileLayer

- website/gatsby-config.js
- website/package.json
Adds the `index` field on `ADDITIONAL_LINKS`, adds the required `STYLESHEETS` field. If we aren't using `Mapbox GL JS` at all in any examples, we could remove the entry, but `STYLESHEETS` needs to be an empty array at least.
With these changes the website builds correctly locally.
> Fix `gatsby-config.js`

- docs/developer-guide/get-started.md
When using an _absolute_ link to the markdown file, the link works on both Github docs and in Gatsby/ocular. Tested on my branch on Github and in Gatsby.
Closes #6.
> Fix link to pydeck-integration

- examples/ee-demo/app.js
- website/gatsby-config.js
- website/package.json
- Add `EE_CLIENT_ID` to `gatsby-plugin-env-variables`
- Make Gatsby load on port 8080. It looks like specific ports have to be whitelisted for use with a given Client ID, and the default Gatsby port of 8000 isn't whitelisted.
Then to start website:
```bash
cd website
yarn
export EE_CLIENT_ID=...
yarn run start
```
Closes #42 , closes #41
> Working example on website

- examples/ee-demo/app.js
Unnecessary for the existing example and requires more-private scopes.
> Remove cloud platform API scope

- modules/earthengine-layers/src/earth-engine-layer.js
- modules/earthengine-layers/src/utils.js
Closes #33. Removes need for custom layer id from #13.
Uses the deep comparison from https://github.com/visgl/deck.gl/blob/master/modules/core/src/utils/deep-equal.js. The list of allowed `visParams` is [here](https://developers.google.com/earth-engine/image_visualization) in the EE docs. There can be nested arrays, but not nested objects, so deeply comparing only arrays should be fine.
> Deep compare visParams

- modules/earthengine-layers/src/earth-engine-layer.js
- modules/earthengine-layers/src/ee-api.js
- modules/earthengine-layers/src/utils.js
Removes custom `promisifyEEAPIs` and instead creates the `Promise` in place. Closes #46.
> Remove custom getMapAsync

- py/pydeck_earthengine_layers/pydeck_earthengine_layers.py
Closes #55 
Means a user can do:
```py
ee_object = ee.ImageCollection('NOAA/GFS0P25').filterDate('2018-12-22', '2018-12-23').limit(24).select('temperature_2m_above_ground')
vis_params = {
"min": -40.0,
"max": 35.0,
"palette": ['blue', 'purple', 'cyan', 'green', 'yellow', 'red']
}
ee_layer = EarthEngineLayer(
ee_object,
vis_params,
animate=True
)
```
whereas currently it's required to pass `vis_params` as a keyword argument, i.e.
```py
ee_layer = EarthEngineLayer(
ee_object,
vis_params=vis_params,
animate=True
)
```
All props other than `ee_object` and `vis_params` are required to be keyword arguments, and I think they should stay that way. I think that users would be used to the EE API, where `eeObject` and `visParams` are the first two positional parameters. `visParams` is still …
> Set vis_params as second positional argument

- examples/ee-demo/app.js
- examples/ee-demo/examples.js
- examples/ee-demo/image-collection-animation.js
- examples/ee-demo/image.js
- examples/ee-demo/index.html
- examples/ee-demo/webpack.config.js
- website/gatsby-config.js
Refactors `app.js` to load examples from an external function, and switch between them based on props. Is this along the lines you were thinking of `ibgreen`? Is this clear enough for users?
> Support multiple JS examples

- examples/image/app.js
- examples/image/index.html
- examples/shared/index.js
- examples/shared/react-components/info-box.js
The login issues are most likely a result of componentDidMount not being called due to [server side rendering](https://jaketrent.com/post/react-componentdidmount-not-called-server-render/) in Gatsby builds.
I moved it back into constructor - this can cause issues if the auto login fires very quickly and the component hasn't been mounted, as setState is only allowed after mount. But this should only happen occasionally in development and the focus right now is to get a working build.
Added info box to Image example - should be duplicated for all examples
> Add Infobox to example. Fix login

- modules/earthengine-layers/src/earth-engine-layer.js
Closes #63 
In some occasions, either 
1. when rendering an image that's been styled using `.style` instead of `visParams` or
2. when rendering data as a vector
We need to call `updateEEVisParams` even if `visParams` hasn't changed. Since `changeFlags.dataChanged` means nothing since we aren't using the `data` prop, this changes that to compare the current and previous `eeObject` prop.
> Run _updateEEVisParams if changed eeObject

- modules/earthengine-layers/package.json
Since building the dist bundles is currently named `build-rollup` instead of `build`, it doesn't get called when `yarn build` is run in the root directory.
> Rename build-rollup to build

- py/pydeck_earthengine_layers/pydeck_earthengine_layers.py
The `modules/earthengine-layers/dist` folder was deleted from Github upon publishing the first betas to NPM. This updates the python module to point to the latest release on NPM, via unpkg.
> Update default bundle url for python package

- py/examples/Introduction.ipynb
- py/examples/international_boundaries.ipynb
- py/examples/noaa_hurricanes.ipynb
- py/examples/power_plants.ipynb
Adds three new pydeck examples. These need to be cleaned up a little more
> Add new pydeck examples

- py/examples/Introduction.ipynb
- py/examples/README.md
NodeJS is a necessary dependency to be able to install Jupyter Lab extensions.
> Update docs to mention nodejs dependency

- examples/power-plants/app.js
For some reason it seems the tooltip div ends up interfering with the pointer, not sure why this became an issue after the switch to Google Maps but a small offset seems to solve it.
> Fix tooltip flicker

- modules/earthengine-layers/package.json
- modules/earthengine-layers/rollup.config.js
- package.json
- website/package.json
- yarn.lock
Fixes Node imports within loaders.gl so that the latest JS bundle can be used successfully in pydeck.
> Bump @loaders.gl to 2.3.0-alpha.10

- modules/earthengine-layers/src/earth-engine-layer.js
- modules/earthengine-layers/src/earth-engine-terrain-layer.js
- Forwards additional props that are new in TileLayer 8.2
- Sets `tileSize` to 256 by default, since PNGs returned from Earth Engine are 256x256px. This renders at higher resolution on hi-dpi displays. The RequestScheduler is still in effect.
> Forward added TileLayer props in 8.2

- modules/earthengine-layers/docs/api-reference/earthengine-layer.md
- modules/earthengine-layers/docs/api-reference/earthengine-terrain-layer.md
- modules/earthengine-layers/package.json
- modules/earthengine-layers/rollup.config.js
- modules/earthengine-layers/src/bundle.js
- modules/earthengine-layers/src/earth-engine-terrain-layer.js
- py/examples/terrain.ipynb
- py/pydeck_earthengine_layers/__init__.py
- py/pydeck_earthengine_layers/pydeck_earthengine_layers.py
- py/setup.cfg
- yarn.lock
Closes #90
Adds the ability to call the EarthEngineTerrainLayer from Python.
- Updates `rollup/plugin-commonjs` to fix some bundling issues with dependencies
- Removes `@luma.gl` from rollup externals. Since we never call luma ourselves anywhere in EarthEngine layer, declaring it as external hid the bundled copy of luma.gl within `deck.gl/geo-layers`
- Adds more `@deck.gl` externals. Full list derived from `jupyter-widget` [here](https://github.com/visgl/deck.gl/blob/c8702ae134e0598b2fdca03642744f25e9de593b/modules/jupyter-widget/src/deck-bundle.js). Otherwise had multiple copies of deck.gl bundled, which caused "Model needs a Program" errors
Questions:
> Pydeck EarthEngineTerrainLayer

- website/package.json
The last time I deployed `earthengine-layers.com` I accidentally forgot to include the Google Maps API Key. This change means that running `yarn build && yarn deploy` will fail if the `EE_CLIENT_ID` and `GoogleMapsAPIKey` aren't set.
> Check environment variables are set before building site

- py/pydeck_earthengine_layers/pydeck_earthengine_layers.py
By default Pydeck does [special handling for prop inputs](https://github.com/visgl/deck.gl/blob/0e9109a9bd79eebb99cdcf9901d45df71500c09d/bindings/pydeck/pydeck/bindings/layer.py#L84-L106). This means that pydeck 0.4.0 can't pass an array of strings to the JS layer without them being considered a function.
This is a workaround "hack" that binds selected layer properties directly to the `Layer` instance instead of passing those properties as `kwargs` (keyword arguments) to the `pydeck.Layer` constructor. This bypasses Pydeck's magic handling of prop inputs.
It works because when Pydeck serializes the layer, it calls `vars(layer)`, which assembles the layer's attributes in a dict.
Ref https://github.com/visgl/deck.gl/pull/4897
> Workaround for pydeck magic/array handling
